version: '3'

services:
  app:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
#    extra_hosts: ## For connecting to local substrate node
#      - "host.docker.internal:host-gateway"
    environment:
      PGHOST: postgres
  backup_collections:
    build:
      context: .
      dockerfile: Dockerfile-backup
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
  postgres:
    container_name: postgres_container
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rmrkuser
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
  nginx:
    build: ./nginx
    ports:
      - "3000:8080"
    depends_on:
      - app
    links:
      - app
volumes:
  postgres: